export const MOCK_DOCUMENTS_DATA = {
    "docs": [
        {
            "id": 3918947,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/350_north_high_street_20250917_124239/auditor/transfers.txt?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=8FSyy6pMT1EEMMf41cLs%2Ffa%2FMN0%3D&Expires=1758132587",
            "documentType": "auditor",
            "summary": "The sales summary shows a transfer of the property at 350 N High St, Columbus, with Parcel ID 010-187792-00, to the City of Columbus on February 5, 1981. No sale price is listed for this transfer.",
            "keywords": "Parcel ID 010-187792-00, City of Columbus, 350 N High St, transfer history, sales summary, February 5, 1981, no sale price, property conveyance",
            "fileExt": "txt",
            "numOfPages": null,
            "numOfWords": 38,
            "fileSize": "0.0002300",
            "notes": "",
            "informationType": "auditor",
            "documentName": "transfers.txt",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:09.023Z",
            "modifiedAt": "2025-09-17T17:04:09.023Z"
        },
        {
            "id": 3918946,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/350_north_high_street_20250917_124239/auditor/tax_n_payments.txt?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=4Z6%2F7sTujHc%2FtH81Ok02Pmf2ufg%3D&Expires=1758132587",
            "documentType": "auditor",
            "summary": "The 2024 property tax statement for 350 N High St, Columbus, shows no delinquent taxes, a net annual tax of $870,426.22, all taxes paid, detailed tax and assessment splits for the current year, and no homestead credits.",
            "keywords": "2024 property tax, no delinquent taxes, net annual tax, special assessments, Columbus auditor, tax payment detail, commercial property, homestead credit",
            "fileExt": "txt",
            "numOfPages": null,
            "numOfWords": 231,
            "fileSize": "0.0014500",
            "notes": "",
            "informationType": "auditor",
            "documentName": "tax_n_payments.txt",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:09.023Z",
            "modifiedAt": "2025-09-17T17:04:09.023Z"
        },
        {
            "id": 3918936,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Tallis_20250917_124239/recorder/tallis_fisher_recorder_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=IjarscYA0BB8C89O4%2BddI8HqqBU%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.1700000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "tallis_fisher_recorder_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918939,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Tallis_20250917_124321/probate/tallis_fisher_probate_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=oPtQ13ryguHQ%2F9kzzgPEkbj2ryg%3D&Expires=1758132587",
            "documentType": "probate",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.3400000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "tallis_fisher_probate_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918940,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Tallis_20250905_034942/probate_marriage/tallis_fisher_probate_marriage_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=ffRdssAgvvV7LX9OAP81o%2FtfvhY%3D&Expires=1758132587",
            "documentType": "probate_marriage",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.3800000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "tallis_fisher_probate_marriage_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918938,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Tallis_20250913_062336/municipal_clerk/tallis_fisher_mc_clerk_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=TlvYCW4mhHqPaQZJUWGSHyR2%2FZQ%3D&Expires=1758132587",
            "documentType": "municipal_clerk",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.8100000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "tallis_fisher_mc_clerk_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918937,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Tallis_20250912_081448/clerk/tallis_fisher_clerk_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=03cAwDl4huzwi9E9sajykjrLJA0%3D&Expires=1758132587",
            "documentType": "clerk_of_courts",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.3100000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "tallis_fisher_clerk_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918945,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/350_north_high_street_20250917_124239/auditor/property_information.txt?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=Pa6sb2ZvvkF5m01goNOnuf30xss%3D&Expires=1758132587",
            "documentType": "auditor",
            "summary": "Property details for 350 N HIGH ST, Columbus, including ownership, legal description, land and building taxable values, site and dwelling data, and tax status information from Franklin County Auditor's Office.",
            "keywords": "Franklin County, parcel number, taxable value, property address, legal description, year built, property class, hotel",
            "fileExt": "txt",
            "numOfPages": null,
            "numOfWords": 442,
            "fileSize": "0.0027700",
            "notes": "",
            "informationType": "auditor",
            "documentName": "property_information.txt",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:09.023Z",
            "modifiedAt": "2025-09-17T17:04:09.023Z"
        },
        {
            "id": 3918941,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Schnugg_Joseph_20250917_124239/recorder/joseph_schnugg_recorder_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=5JPOUaqMj4Q0ZXXeGi3xS48EO2Q%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.1700000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "joseph_schnugg_recorder_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918942,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Schnugg_Joseph_20250905_034942/probate_marriage/joseph_schnugg_probate_marriage_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=3JPMmddJOvr22P55MwIQqIIiR%2BE%3D&Expires=1758132587",
            "documentType": "probate_marriage",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.4000000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "joseph_schnugg_probate_marriage_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918943,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Schnugg_Jessica_20250917_124326/recorder/jessica_schnugg_recorder_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=uiJf3XqweSe0OLnZNsmnADr99Sg%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.1700000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "jessica_schnugg_recorder_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918944,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Schnugg_Jessica_20250905_034942/probate_marriage/jessica_schnugg_probate_marriage_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=ySgp5E0nkqRPdnptnM9%2Fay5dSvc%3D&Expires=1758132587",
            "documentType": "probate_marriage",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.4000000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "jessica_schnugg_probate_marriage_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918929,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/_CITY_COLUMBUS_20250917_124430/recorder/city%20columbus__recorder_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=gZfUBNZrzFY7dt6SVSE0tefuuqQ%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.1800000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "city columbus__recorder_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918930,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/_CITY_COLUMBUS_20250913_062336/municipal_clerk/city%20columbus__mc_clerk_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=gfGIJwK3QHWtq7do%2F2mI08mI1Hw%3D&Expires=1758132587",
            "documentType": "municipal_clerk",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 4,
            "numOfWords": null,
            "fileSize": "1.8800000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "city columbus__mc_clerk_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918949,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/350_north_high_street_20250917_124239/auditor/city%20columbus__auditor_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=%2FDXiubk28d3Q3mZlSe6kHzHoIeU%3D&Expires=1758132587",
            "documentType": "auditor",
            "summary": "",
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 9,
            "numOfWords": null,
            "fileSize": "2.4400000",
            "notes": "",
            "informationType": "auditor",
            "documentName": "city columbus__auditor_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:09.023Z",
            "modifiedAt": "2025-09-17T17:04:09.023Z"
        },
        {
            "id": 3918931,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Chase_20250917_124239/recorder/chase_fisher_recorder_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=jm8504dmh4eYZ7Qq6y%2FWE9y8%2BL4%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.1700000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "chase_fisher_recorder_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918934,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Chase_20250917_124321/probate/chase_fisher_probate_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=jYzKKxvjQqvdOMxB%2FXLr4%2F%2BJzQg%3D&Expires=1758132587",
            "documentType": "probate",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.3700000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "chase_fisher_probate_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918935,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Chase_20250905_034942/probate_marriage/chase_fisher_probate_marriage_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=UwmLJTWpKOswu5NWYOqdqIBQCLA%3D&Expires=1758132587",
            "documentType": "probate_marriage",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.3900000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "chase_fisher_probate_marriage_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918933,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Chase_20250913_062336/municipal_clerk/chase_fisher_mc_clerk_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=vJEgkxAY%2Fg8Uz8UcnhQ0ShuBnU8%3D&Expires=1758132587",
            "documentType": "municipal_clerk",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.8100000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "chase_fisher_mc_clerk_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918932,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/Fisher_Chase_20250912_081448/clerk/chase_fisher_clerk_ss.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=sjh9vzzN9tV6Q%2Fa4661b9DGczWs%3D&Expires=1758132587",
            "documentType": "clerk_of_courts",
            "summary": null,
            "keywords": "",
            "fileExt": "pdf",
            "numOfPages": 2,
            "numOfWords": null,
            "fileSize": "0.3100000",
            "notes": null,
            "informationType": "screenshots",
            "documentName": "chase_fisher_clerk_ss",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:08.980Z",
            "modifiedAt": "2025-09-17T17:04:08.980Z"
        },
        {
            "id": 3918948,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": null,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/350_north_high_street_20250917_124239/auditor/bor_status.txt?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=Sil9k6SPFWmRzZBvtMKojeoZb08%3D&Expires=1758132587",
            "documentType": "auditor",
            "summary": "The Board of Revision (BOR) case number 2020-003154 for the year 2020 is finalized and non-appealed, with a counter complaint noted. No hearing or mailing dates are provided in the record.",
            "keywords": "BOR case, finalized, non-appeal, 2020, counter complaint, Board of Revision, case status, Columbus",
            "fileExt": "txt",
            "numOfPages": null,
            "numOfWords": 130,
            "fileSize": "0.0008200",
            "notes": "",
            "informationType": "auditor",
            "documentName": "bor_status.txt",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:09.023Z",
            "modifiedAt": "2025-09-17T17:04:09.023Z"
        },
        {
            "id": 3918955,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": 2621,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/_CITY_COLUMBUS_20250917_124430/recorder/Released/MECHANICS%20LIEN/199001120051434.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=TyKWHMTBHPJ%2F6rle5Ojq711ydkQ%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": "A mechanics lien was filed by Sterling Electric Company against retail space at 192 Columbus City Center Drive, Columbus, OH, for $10,377.30 due from Dave Osborne Construction Contracting, Inc. The document details property legal description and was recorded January 12, 1990.",
            "keywords": "mechanics lien, Sterling Electric, Dave Osborne Construction, 192 Columbus City Center Drive, Columbus Ohio, property lien, released, January 1990",
            "fileExt": "pdf",
            "numOfPages": 3,
            "numOfWords": 1506,
            "fileSize": "0.2381500",
            "notes": "",
            "informationType": "MECHANICS LIEN",
            "documentName": "199001120051434.pdf",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:10.315Z",
            "modifiedAt": "2025-09-17T17:04:10.315Z"
        },
        {
            "id": 3918950,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": 2621,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/_CITY_COLUMBUS_20250917_124430/recorder/Active/MORTGAGE/197710130027388.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=cuf2X9dj417AyL1iTkRDKGQJJHM%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": "This is an open end mortgage executed by Gregory & Frances Price in favor of the City of Columbus for $5,500, secured against 514 Clinton, Columbus, Ohio. Mortgage dated September 27, 1977, recorded October 11, 1977, with terms for default, insurance, and foreclosure.",
            "keywords": "Open End Mortgage, Gregory Price, Frances Price, City of Columbus, 514 Clinton, Indianola Terrace Subdivision, Franklin County, 1977",
            "fileExt": "pdf",
            "numOfPages": 4,
            "numOfWords": 1706,
            "fileSize": "0.1224600",
            "notes": "",
            "informationType": "mortgage",
            "documentName": "197710130027388.pdf",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:10.315Z",
            "modifiedAt": "2025-09-17T17:04:10.315Z"
        },
        {
            "id": 3918953,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": 2621,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/_CITY_COLUMBUS_20250917_124430/recorder/Active/MORTGAGE/197710130027387.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=3GSYHxl11Y9HH9I4mfSSeGGoWCk%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": "Open End Mortgage by Wesley & Audrey Schofield to City of Columbus for $3,950, secured by two properties at 1039 Ann Street, Columbus, Ohio. Legal covers two subdivision lots. Recorded 1977-10-13.",
            "keywords": "Open End Mortgage, City of Columbus, Wesley Schofield, Audrey Schofield, Multiple properties, 1039 Ann Street, Jacob Bleile's Subdivision, Blanket mortgage",
            "fileExt": "pdf",
            "numOfPages": 4,
            "numOfWords": 1752,
            "fileSize": "0.1233300",
            "notes": "",
            "informationType": "mortgage",
            "documentName": "197710130027387.pdf",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:10.315Z",
            "modifiedAt": "2025-09-17T17:04:10.315Z"
        },
        {
            "id": 3918952,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": 2621,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/_CITY_COLUMBUS_20250917_124430/recorder/Active/MORTGAGE/197710130027386.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=mPdEOosvq6PeKRpFLfzXur0hcGo%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": "An Open End Mortgage recorded on September 27, 1977, by Sharyn Sue Lewis in favor of the City of Columbus Department of Development for $15,050, securing property at 969 Hunter Avenue, Columbus, Ohio, covering lots 139, 140, and 141.",
            "keywords": "Open End Mortgage, Sharyn Sue Lewis, City of Columbus Department of Development, 969 Hunter Avenue, Columbus Ohio, plat book, legal description, real estate",
            "fileExt": "pdf",
            "numOfPages": 4,
            "numOfWords": 1798,
            "fileSize": "0.1247500",
            "notes": "",
            "informationType": "mortgage",
            "documentName": "197710130027386.pdf",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:10.315Z",
            "modifiedAt": "2025-09-17T17:04:10.315Z"
        },
        {
            "id": 3918951,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": 2621,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/_CITY_COLUMBUS_20250917_124430/recorder/Active/MORTGAGE/197710130027385.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=eM0ve5l9L0OsNZjBHPomrhXrQ0M%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": "Open End Mortgage from Equillare & Helen Bowers to City of Columbus Department of Development securing $11,900 on property at 1514 E. Hudson St, Columbus, OH, dated September 27, 1977 and recorded October 13, 1977, for 20 years.",
            "keywords": "Open End Mortgage, City of Columbus, 1514 E. Hudson Street, Franklin County, Equillare Bowers, Helen Bowers, Highway Park Addition, Mortgage 1977",
            "fileExt": "pdf",
            "numOfPages": 4,
            "numOfWords": 1721,
            "fileSize": "0.1226200",
            "notes": "",
            "informationType": "mortgage",
            "documentName": "197710130027385.pdf",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:10.315Z",
            "modifiedAt": "2025-09-17T17:04:10.315Z"
        },
        {
            "id": 3918954,
            "titleSearchId": 854,
            "purchaseContractId": null,
            "stakeholderId": 2621,
            "originalRefId": null,
            "propertyId": null,
            "documentPath": "https://scraped-results-1.s3.amazonaws.com/_CITY_COLUMBUS_20250917_124430/recorder/Active/MISCELLANEOUS/190505154890288.pdf?AWSAccessKeyId=AKIA4IENJYES7HDKI3EM&Signature=s1oiFqVAUFDgP%2BKoxI5YfMIeYw0%3D&Expires=1758132587",
            "documentType": "recorder",
            "summary": "This 1905 contract between the City of Columbus and Susan H. Sanders grants a permit to construct and maintain covered areas under sidewalks on specific streets. It outlines responsibilities, liability terms, and stipulations for maintaining public rights.",
            "keywords": "City of Columbus, covered sidewalk areas, Susan H. Sanders, permit, public right-of-way, maintenance agreement, construction contract, liability",
            "fileExt": "pdf",
            "numOfPages": 4,
            "numOfWords": 1093,
            "fileSize": "0.3926000",
            "notes": "",
            "informationType": "MISCELLANEOUS",
            "documentName": "190505154890288.pdf",
            "createdBy": null,
            "modifiedBy": null,
            "createdAt": "2025-09-17T17:04:10.315Z",
            "modifiedAt": "2025-09-17T17:04:10.315Z"
        }
    ],
    "count": 21
}
